title: "Mi blog con Tufte"
description: "Demo mínima con posts"
markdown: kramdown
timezone: Europe/Madrid
future: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme   # <- necesario

remote_theme: clayh53/tufte-jekyll
